### ISSUE TITLE
Is -fno-rtti really needed? 

### ISSUE THREAD

**Issue by mgerhardy** [fungos/fips-turbobadger#2]
getting unresolved symbol linker error for typeinfo of tb::TBRendererBatcher with my own ui renderer implementation. I do need rtti in e.g. the fips-sauce module.

**Comment by mgerhardy** [comment]
and if not - maybe you could provide a flag for enable/disable this?

**Comment by fungos** [comment]
Maybe not, as exceptions I've followed the original CMakeLists.txt on this. Will add an option for RTTI. Is there something on FIPS for this as there is for exceptions?

**Comment by fungos** [comment]
Fixed, can you try it and see if it is ok for you?

**Comment by mgerhardy** [comment]
for some reason this doesn't work

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8f86014..d68a8c0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,6 +9,8 @@ include(CheckLibraryExists)

 set(FIPS_EXCEPTIONS ON)
 set(FIPS_UNITTESTS ON)
+set(TB_ENABLE_RTTI ON)
+set(TB_DISABLE_SAMPLES ON)

^^ this is my change set for my cmake file - but it somehow still adds -fno-rtti - once I remove it manually it works fine.

**Comment by fungos** [comment]
I'll take another look, will try to import it in another project and check what is happening. Thanks.

**Comment by mgerhardy** [comment]
Even though my other ticket that didn't work was a mystery fix - this is still an issue for me. Even after doing a complete fresh checkout of my project and all fips related stuff.

**Comment by fungos** [comment]
It looks like a cmake cache problem. Can you try to add this to the begining of your CMakeLists.txt?

set(TB_ENABLE_RTTI ON CACHE BOOL "Do not disable RTTI" FORCE)

Maybe you should do the same for TB_DISABLE_SAMPLES to be sure.

**Comment by mgerhardy** [comment]
Thanks a lot - that fixed it (still weird because I did a fresh checkout before) - thanks again.
